version: '3'

# To build and start stack:
# docker-compose build; docker-compose up -d
#
# To stop stack:
# docker-compose down
services:

  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      CONNECTION_STRING: mongodb://root:password@mongo:27017
      PORT: 5000
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
