name: Build and deploy multiarch image 

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'main'
      - 'releases/v*'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          IMG_NAME: ${{ 'krishnaalagiri/ssm' }}
          # Versioning: MAJOR.MINOR.PATCH (eg., 1.2.3)
          VERSION_FULL: ${{ '1.1.0' }}
          # For v1.2.3, VERSION_SHORT is '1.2'
          VERSION_SHORT: ${{ '1.1' }}
          # For v1.2.3, VERSION_MAJOR is '1'
          VERSION_MAJOR: ${{ '1' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMG_NAME }}:latest,${{ env.IMG_NAME }}:${{ env.VERSION_FULL }},${{ env.IMG_NAME }}:${{ env.VERSION_SHORT }},${{ env.IMG_NAME }}:${{ env.VERSION_MAJOR }} 
